services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gestionmssql2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  api:
    build: .
    image: expedientes-indicios-api:1.0.0
    container_name: expedientes-api
    env_file:
      - .env
    # Si quisieras sobrescribir algo, podrías agregar environment: con claves puntuales
    depends_on:
      - mssql
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  mssql-data:
